In [3]:
import sqlite3
import pandas as pd
# Create connection
# Write a query that will return the artist name, album title, and genre name into a dataframe
# Show the dataframe
db_file = '../assignments/chinook.db'
cnn = sqlite3.connect(db_file)
df= pd.read_sql_query(f"""SELECT albums.Title as album_title, artists.name as artist_name, genres.name as genre_name 
                      FROM albums JOIN artists on albums.artistid = artists.artistid 
                      JOIN tracks on tracks.albumid = albums.albumid 
                      JOIN genres on tracks.genreid = genres.genreid;""", cnn)

df

,album_title,artist_name,genre_name
0,For Those About To Rock We Salute You,AC/DC,Rock
1,For Those About To Rock We Salute You,AC/DC,Rock
2,For Those About To Rock We Salute You,AC/DC,Rock
3,For Those About To Rock We Salute You,AC/DC,Rock
4,For Those About To Rock We Salute You,AC/DC,Rock
...,...,...,...
3498,Respighi:Pines of Rome,Eugene Ormandy,Classical
3499,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet,Classical
3500,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...",Classical
3501,Mozart: Chamber Music,Nash Ensemble,Classical
3502,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble,Soundtrack